import { existsSync } from "node:fs";
import { join, normalize } from "node:path";
import { importCursorCsv } from "../core/ingest/cursor.ts";
import { type CursorSyncState, syncState } from "../core/cursorSync.ts";
import { DbWriter, recomputeCosts } from "../core/ingest/writer.ts";
import { branchDetail, branches } from "../core/branches.ts";
import { LINES_DIMS, lines, linesSeries, sessionLines } from "../core/changes.ts";
import { type DigestWeek, digestDir, lastDigest } from "../core/digest.ts";
import { drift } from "../core/drift.ts";
import { friction } from "../core/friction.ts";
import { parseSettings } from "../core/config.ts";
import { defaultDbPath } from "../core/paths.ts";
import type { Bucket, Dimension, Filters, Metric, SeriesGroup } from "../core/queries.ts";
import { SHARED_FOLDER, dbTarget, findSyncFolders } from "../core/syncFolders.ts";
import { activePlans } from "../core/limits.ts";
import { limitHistory, planValue } from "../core/plans.ts";
import { budgetStatus, message } from "../core/budgets.ts";
import { generateTips } from "../core/tips.ts";
import { addTag, allTags, projectRules, removeTag, sessionTags, setNote, setProjectRules } from "../core/tags.ts";
import { clearLabel, isKind, sessionLabel, setKind } from "../core/labels.ts";
import { kindUsage, tagUsage } from "../core/tagUsage.ts";
import { timing } from "../core/timing.ts";
import { CONTENT_TYPE, metricsText } from "../core/metrics.ts";
import { VERSION } from "../version.ts";
import type { App } from "./app.ts";
import { cookieName, cookieValue, sameToken } from "./auth.ts";
import { notify } from "./notify.ts";
import { type FolderPicker, PickerBusy, folderPicker, listDirs, nativeAvailable } from "./pickFolder.ts";
import { applyUpdate, checkForUpdate, isCompiledBinary } from "./update.ts";

const DIMENSIONS: Dimension[] = ["provider", "project", "user", "model", "skill", "agent", "session", "prompt", "host"];
const BUCKETS: Bucket[] = ["hour", "day", "week", "month"];
const GROUPS: SeriesGroup[] = ["none", "type", "provider", "project", "user", "model", "skill", "agent"];

export function parseFilters(sp: URLSearchParams): Filters {
  const n = (k: string) => {
    const v = sp.get(k);
    if (!v) return undefined;
    const x = Number(v);
    return Number.isFinite(x) ? x : undefined;
  };
  const s = (k: string) => sp.get(k) || undefined;
  return { from: n("from"), to: n("to"), provider: s("provider"), project: s("project"), user: s("user"), model: s("model"), skill: s("skill"), agent: s("agent"), tag: s("tag")?.trim().toLowerCase().slice(0, 100), kind: isKind(sp.get("kind")) ? sp.get("kind")! : undefined };
}

function pick<T extends string>(v: string | null, allowed: readonly T[], fallback: T): T {
  return v && (allowed as readonly string[]).includes(v) ? (v as T) : fallback;
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" },
  });
}

/** What Settings shows about the Cursor sync: times, rows and a fixed code, nothing about the login. */
function cursorSyncStatus(app: App, s: CursorSyncState) {
  return { enabled: app.cfg.cursorSync, syncedAt: s.syncedAt, added: s.added, triedAt: s.triedAt, code: s.code, nextAt: s.nextAt };
}

function error(message: string, status = 400): Response {
  return json({ error: message }, status);
}

export interface AssetSource {
  get(path: string): Promise<Response | null>;
}

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
  ".woff2": "font/woff2",
  ".webmanifest": "application/manifest+json",
};

export function mimeFor(path: string): string {
  const ext = path.slice(path.lastIndexOf("."));
  return MIME[ext] ?? "application/octet-stream";
}

/** Serves the built UI either from assets embedded in the binary or from web/dist on disk. */
export async function loadAssets(): Promise<AssetSource> {
  try {
    // Generated by scripts/build.ts right before `bun build --compile`; absent in dev checkouts.
    // @ts-ignore -- optional module
    const mod = (await import("./assets.generated.ts")) as { ASSETS: Record<string, string> };
    if (Object.keys(mod.ASSETS).length) {
      return {
        async get(path) {
          const file = mod.ASSETS[path];
          if (!file) return null;
          return new Response(Bun.file(file), { headers: { "Content-Type": mimeFor(path), "Cache-Control": path.startsWith("/assets/") ? "public, max-age=31536000, immutable" : "no-cache" } });
        },
      };
    }
  } catch {
    /* not generated: development checkout */
  }
  const dist = join(import.meta.dir, "..", "..", "web", "dist");
  return {
    async get(path) {
      const full = normalize(join(dist, path));
      if (!full.startsWith(dist) || !existsSync(full)) return null;
      return new Response(Bun.file(full), { headers: { "Content-Type": mimeFor(path), "Cache-Control": "no-cache" } });
    },
  };
}

/** Who may use the API: the browser with the sign-in cookie, or a program sending the token as a bearer token. */
export interface ServerAuth {
  token: string;
  port: number;
}

export interface ServerHooks {
  /** Called after a self-update installed a new binary; should restart the process. */
  restart(): void;
  /** Stops the background server (the "Quit" button). */
  shutdown(): void;
}

const LOOPBACK = ["localhost", "127.0.0.1", "::1"];

/** The version the live stream reports to a window that isn't signed in (the UI checks for it by name). */
export const SIGNED_OUT = "signed-out";

/**
 * Guards against DNS-rebinding and cross-site requests: the Host header must be a loopback name, and state-changing
 * requests must carry a custom header (which forces a CORS preflight we never allow). The API also refuses requests a
 * browser marks as coming from another site: they can't read the answer, but even a GET has effects here (a scan, a
 * signed-in plan-limit check, an update check). The metrics endpoint is held to the same rules: a page has no business
 * reading it either.
 */
function isAllowed(req: Request, url: URL): boolean {
  const host = (req.headers.get("host") ?? "").replace(/:\d+$/, "").replace(/^\[|\]$/g, "");
  if (!LOOPBACK.includes(host)) return false;
  // The sign-in link may come from anywhere (a terminal, a launcher, a bookmark): it only sets the cookie for the
  // right token, which no other site knows.
  if ((!url.pathname.startsWith("/api/") && url.pathname !== "/metrics") || url.pathname === "/api/auth") return true;
  const site = req.headers.get("sec-fetch-site");
  if (site && site !== "same-origin" && site !== "none") return false;
  const origin = req.headers.get("origin");
  if (origin && !isLoopbackOrigin(origin)) return false;
  if (req.method !== "GET" && req.method !== "HEAD") return !!req.headers.get("x-harness-dashboard");
  return true;
}

function isLoopbackOrigin(origin: string): boolean {
  try {
    const u = new URL(origin);
    return u.protocol === "http:" && LOOPBACK.includes(u.hostname.replace(/^\[|\]$/g, ""));
  } catch {
    return false; // "null": a sandboxed frame or a file
  }
}

/**
 * Sent with every response. No other page may frame the app (clickjacking onto Quit or Install & restart), scripts
 * only come from the app itself, and nothing about it leaks through referrers or cross-origin reads.
 */
const SECURITY_HEADERS: Record<string, string> = {
  "Content-Security-Policy":
    "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
  "X-Frame-Options": "DENY",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "no-referrer",
  "Cross-Origin-Opener-Policy": "same-origin",
  "Cross-Origin-Resource-Policy": "same-origin",
};

function secured(res: Response): Response {
  for (const [k, v] of Object.entries(SECURITY_HEADERS)) res.headers.set(k, v);
  return res;
}

/** A request's JSON body, or undefined when it isn't JSON. */
async function jsonBody(req: Request): Promise<unknown> {
  try {
    return await req.json();
  } catch {
    return undefined;
  }
}

const isPrice = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v) && v >= 0;
const optionalPrice = (v: unknown): number | null => (isPrice(v) ? v : null);

export function createHandler(app: App, assets: AssetSource, hooks: ServerHooks, auth?: ServerAuth, picker: FolderPicker = folderPicker) {
  const cookie = auth ? cookieName(auth.port) : "";
  const signedIn = (req: Request) =>
    !auth || sameToken(req.headers.get("authorization")?.replace(/^Bearer /, ""), auth.token) || sameToken(cookieValue(req.headers.get("cookie"), cookie), auth.token);

  return async function handle(req: Request): Promise<Response> {
    return secured(await respond(req));
  };

  async function respond(req: Request): Promise<Response> {
    const url = new URL(req.url);
    if (!isAllowed(req, url)) return error("forbidden", 403);
    const sp = url.searchParams;
    const path = url.pathname;

    // The sign-in link is the app's root with the token ("/?k=…"): the address the app window opens with names it on
    // Linux (its Wayland app ID and WM class come from the address's path), so it must stay "/" for the launcher that
    // gives the window its icon. "/api/auth?k=…" from 1.11 still works.
    if (auth && (path === "/api/auth" || (path === "/" && sp.has("k")))) {
      if (!sameToken(sp.get("k"), auth.token)) return error("unauthorized", 401);
      return new Response(null, {
        status: 303,
        headers: { Location: "/", "Cache-Control": "no-store", "Set-Cookie": `${cookie}=${auth.token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=31536000` },
      });
    }
    if (path === "/metrics") return metrics(req);
    if (path === "/api/events" && !signedIn(req)) return signedOutEvents();
    if (path.startsWith("/api/") && !signedIn(req)) return error("unauthorized", 401);

    try {
      if (path.startsWith("/api/")) return await api(req, url, path, sp);
      const res = (await assets.get(path === "/" ? "/index.html" : path)) ?? (await assets.get("/index.html"));
      return res ?? new Response("UI not built. Run `bun run build:web`.", { status: 404 });
    } catch (err) {
      console.error("[http]", err);
      return error((err as Error).message, 500);
    }
  }

  /**
   * The Prometheus endpoint: not there unless turned on in Settings, then only for the metrics token as a bearer token.
   * That token is not the app's: a scraper that holds it can read these numbers and nothing else.
   */
  function metrics(req: Request): Response {
    const cfg = app.cfg.metrics;
    if (!cfg.enabled) return error("no route for GET /metrics", 404);
    if (req.method !== "GET" && req.method !== "HEAD") return new Response("method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } });
    const given = /^Bearer\s+(\S+)$/i.exec(req.headers.get("authorization") ?? "")?.[1];
    if (!cfg.token || !sameToken(given, cfg.token)) return new Response("unauthorized", { status: 401, headers: { "WWW-Authenticate": "Bearer", "Cache-Control": "no-store" } });
    const { user, host } = app.identity;
    const body = metricsText({ db: app.db, queries: app.queries, budgets: app.cfg.budgets, projectLabels: cfg.projectLabels, user, host, version: VERSION, lastScanAt: app.lastScanAt });
    return new Response(req.method === "HEAD" ? null : body, { headers: { "Content-Type": CONTENT_TYPE, "Cache-Control": "no-store" } });
  }

  /** A page of a server-paged list: at most 200 rows, or 10000 for an export of the whole list (`export=1`). */
  function pageLimit(sp: URLSearchParams): number {
    const n = Number(sp.get("limit") ?? 50);
    return Math.max(0, Math.min(sp.get("export") === "1" ? 10000 : 200, Number.isFinite(n) ? Math.floor(n) : 50));
  }

  async function api(req: Request, url: URL, path: string, sp: URLSearchParams): Promise<Response> {
    const f = parseFilters(sp);
    const q = app.queries;
    const method = req.method;

    if (method === "GET") {
      switch (path) {
        case "/api/status":
          return json({
            version: VERSION,
            dbPath: app.dbPath,
            scanning: app.isScanning,
            lastScanAt: app.lastScanAt,
            lastScan: app.lastScan,
            identity: app.identity,
            compiled: isCompiledBinary(),
            platform: `${process.platform}-${process.arch}`,
          });
        case "/api/summary":
          return json(q.summary(f));
        case "/api/timeseries":
          return json(q.timeseries(f, pick(sp.get("bucket"), BUCKETS, "day"), pick(sp.get("group"), GROUPS, "type"), pick<Metric>(sp.get("metric"), ["tokens", "cost"], "tokens"), Number(sp.get("top") ?? 5)));
        case "/api/breakdown":
          return json(q.breakdown(f, pick(sp.get("dim"), DIMENSIONS, "project"), Math.min(500, Number(sp.get("limit") ?? 50)), pick(sp.get("sort"), ["tokens", "cost"] as const, "cost")));
        case "/api/drift":
          return json(drift(app.db, f, { model: sp.get("select"), effort: sp.get("effort") }));
        case "/api/billing":
          return json(q.billing(f));
        case "/api/heatmap":
          return json(q.heatmap(f, pick<Metric>(sp.get("metric"), ["tokens", "cost"], "tokens")));
        case "/api/calendar":
          return json(q.calendar(f));
        case "/api/sessions":
          return json(q.sessions(f, { sort: sp.get("sort") ?? undefined, limit: pageLimit(sp), offset: Number(sp.get("offset") ?? 0), q: sp.get("q") ?? undefined }));
        case "/api/session": {
          const id = sp.get("id") ?? "";
          const detail = q.sessionDetail(id);
          return json({ ...detail, lines: sessionLines(app.db, id, detail.totals?.cost ?? 0), ...sessionTags(app.db, id), label: sessionLabel(app.db, id) });
        }
        case "/api/kinds":
          return json(kindUsage(app.db, f));
        case "/api/labels":
          return json(app.labelStatus());
        case "/api/tags":
          return json(tagUsage(app.db, f));
        case "/api/tags/all":
          return json(allTags(app.db));
        case "/api/tags/rules":
          return json(projectRules(app.db));
        case "/api/lines":
          return json(lines(app.db, f, sp.has("dim") ? pick(sp.get("dim"), LINES_DIMS, "model") : undefined));
        case "/api/lines/series":
          return json(linesSeries(app.db, f, pick(sp.get("bucket"), BUCKETS, "day")));
        case "/api/prompts":
          return json(q.prompts(f, { sort: sp.get("sort") ?? undefined, limit: pageLimit(sp), offset: Number(sp.get("offset") ?? 0), q: sp.get("q") ?? undefined }));
        case "/api/prompts/stats":
          return json(q.promptStats(f, pick(sp.get("metric"), ["tokens", "cost"] as const, "cost")));
        case "/api/prompt":
          return json(q.promptDetail(sp.get("id") ?? ""));
        case "/api/tools":
          return json(q.tools(f));
        case "/api/files":
          return json(q.files(f));
        case "/api/files/hotspots":
          return json(q.hotspots(f));
        case "/api/files/list":
          return json(q.fileList(f, { sort: sp.get("sort") ?? undefined, limit: pageLimit(sp), offset: Number(sp.get("offset") ?? 0), q: sp.get("q") ?? undefined }));
        case "/api/cache":
          return json(q.cache(f, pick(sp.get("bucket"), BUCKETS, "day")));
        case "/api/branches":
          return json(branches(app.db, f));
        case "/api/branch":
          return json(branchDetail(app.db, sp.get("id") ?? ""));
        case "/api/friction":
          return json(friction(app.db, f, pick(sp.get("bucket"), BUCKETS, "day")));
        case "/api/time":
          return json(timing(app.db, f, pick(sp.get("bucket"), BUCKETS, "day")));
        case "/api/plans":
          return json({ ...planValue(app.db, f, pick(sp.get("bucket"), BUCKETS, "day"), app.cfg.planPrices), history: limitHistory(app.db, f) });
        case "/api/tips":
          return json(generateTips(app.db, f, app.priceBook()));
        case "/api/tips/state":
          return json(app.cfg.tips);
        case "/api/live": {
          // The page polls this once a minute: scan first, so the answer includes what was written since the last scan.
          if (Date.now() - (app.lastScanAt ?? 0) > 10_000) await app.scanNow().catch(() => {});
          const minutes = Math.min(360, Math.max(5, Math.round(Number(sp.get("minutes")) || 60)));
          return json(q.live(f, minutes));
        }
        case "/api/limits": {
          // With `minutes`, only the plans the sessions of that window ran on are asked about.
          const minutes = Number(sp.get("minutes"));
          const active = minutes > 0 ? activePlans(app.db, Date.now() - minutes * 60_000) : undefined;
          const result = await app.limits.get(app.db, app.identity.host, app.cfg.limits, sp.get("force") === "1", active);
          app.sendAlerts(result.reports).catch((err) => console.error("[alerts]", err));
          return json({ ...result, active: active ?? null });
        }
        case "/api/cursor/sync":
          return json(cursorSyncStatus(app, syncState(app.db, app.identity.host)));
        case "/api/digest":
          // The latest digest this machine wrote, for the view in Settings, and the folder they go to.
          return json({ last: lastDigest(app.db, app.identity.host), dir: digestDir(app.cfg.digest) });
        case "/api/budgets": {
          const b = app.cfg.budgets;
          return json({ config: b, items: budgetStatus(app.db, b, app.identity.user) });
        }
        case "/api/filters":
          return json(q.filters(f));
        case "/api/settings":
          return json({ config: app.cfg, dbPath: app.dbPath, defaultDbPath: defaultDbPath(), syncFolders: findSyncFolders(), sharedFolder: SHARED_FOLDER });
        case "/api/pick-folder/available":
          return json({ native: nativeAvailable() });
        case "/api/dirs": {
          const r = listDirs(sp.get("path") ?? "", sp.get("hidden") === "1");
          return "error" in r ? error(r.error, r.error === "not-absolute" ? 400 : r.error === "denied" ? 403 : 404) : json(r);
        }
        case "/api/db/size":
          return json(app.dbSize());
        case "/api/settings/db-target":
          return json(dbTarget(sp.get("path") ?? "", app.dbPath, defaultDbPath()));
        case "/api/pricing":
          return json(app.priceBook().allRules());
        case "/api/update":
          return json(app.cfg.checkUpdates || sp.get("force") ? await checkForUpdate(sp.get("force") === "1") : { current: VERSION, available: false, disabled: true });
        case "/api/events":
          return events(req);
      }
    }

    if (method === "POST" || method === "PUT" || method === "DELETE") {
      if (method === "DELETE" && path !== "/api/tags" && path !== "/api/session/label") return error(`no route for ${method} ${url.pathname}`, 404);
      switch (path) {
        // Tags and notes are the user's own data: written here, never by a scan. { session, tag } and { session, note }.
        case "/api/tags":
        case "/api/session/note":
        case "/api/tags/rules": {
          const body = (await jsonBody(req)) as Record<string, unknown> | undefined;
          if (!body || typeof body !== "object") return error("expected a JSON object");
          let result;
          if (path === "/api/tags/rules" && method === "PUT") result = setProjectRules(app.db, body.rules);
          else if (path === "/api/session/note" && method === "PUT") result = setNote(app.db, body.session, body.note);
          else if (path === "/api/tags" && method === "POST") result = addTag(app.db, body.session, body.tag);
          else if (path === "/api/tags" && method === "DELETE") result = removeTag(app.db, body.session, body.tag);
          else return error(`no route for ${method} ${url.pathname}`, 404);
          if ("error" in result) return error(result.error);
          return json(result.ok);
        }
        // AI labels: the user's own opt-in. Label now, a regenerate for one session, a kind set by hand, a label cleared.
        case "/api/labels/run":
          return json({ ...(await app.labelSessions({ force: true })), ...app.labelStatus() });
        case "/api/session/label": {
          const body = (await jsonBody(req)) as Record<string, unknown> | undefined;
          if (!body || typeof body !== "object") return error("expected a JSON object");
          const id = body.session;
          if (method === "PUT") {
            const result = setKind(app.db, id, body.kind);
            if ("error" in result) return error(result.error);
            return json(result.ok);
          }
          if (method === "DELETE") {
            const result = clearLabel(app.db, id);
            return "error" in result ? error(result.error) : json(null);
          }
          if (typeof id !== "string" || !id || id.length > 500) return error("invalid value for session");
          if (!app.cfg.labels.enabled) return error("labels are off");
          const run = await app.labelSessions({ ids: [id] });
          return json({ run, label: sessionLabel(app.db, id) });
        }
        case "/api/scan": {
          const result = await app.scanNow(sp.get("full") === "1");
          return json(result);
        }
        case "/api/cursor/sync":
          // Sync now: asks cursor.com right away, unless it asked to wait or the sync is off.
          return json(cursorSyncStatus(app, await app.syncCursor(true)));
        case "/api/import/cursor": {
          const text = await req.text();
          const writer = new DbWriter(app.db, app.priceBook(), app.identity);
          let result;
          app.db.transaction(() => {
            result = importCursorCsv(text, writer);
          })();
          app.emit({ type: "scan", result: { filesSeen: 0, filesParsed: 1, usageRows: writer.stats.usage, prompts: 0, tools: 0, errors: [], durationMs: 0 } });
          return json(result);
        }
        case "/api/settings": {
          const body = await jsonBody(req);
          const parsed = parseSettings(body);
          if ("error" in parsed) return error(parsed.error);
          const { dbPath, copyDb } = body as { dbPath?: unknown; copyDb?: unknown };
          if (dbPath !== undefined && (typeof dbPath !== "string" || dbPath.length > 4096)) return error("invalid value for dbPath");
          const patch = parsed.patch;
          app.updateConfig(patch);
          if (typeof dbPath === "string") {
            const target = dbTarget(dbPath, app.dbPath, defaultDbPath());
            if (target.state === "missing" || target.state === "invalid") return error(`Can't use ${target.file}: ${target.state === "missing" ? "its folder doesn't exist" : "the path isn't absolute"}`);
            const file = target.state === "default" ? "" : target.file;
            if (target.state !== "current" && file !== app.cfg.dbPath) await app.switchDatabase(file, copyDb === true);
          }
          if (patch.sources) app.scanNow().catch(() => {});
          // A cap set below what is spent already alerts now, not with the next usage.
          if (patch.budgets) app.sendAlerts().catch((err) => console.error("[alerts]", err));
          return json({ config: app.cfg, dbPath: app.dbPath });
        }
        case "/api/tips/state": {
          // Lists of ids to add to or take out of each set: { hide, unhide, read, unread }.
          const body = ((await jsonBody(req)) ?? {}) as Record<string, unknown>;
          const ids = (k: string) => (Array.isArray(body[k]) ? (body[k] as unknown[]).filter((v): v is string => typeof v === "string" && v.length <= 300) : []);
          const apply = (list: string[], add: string[], remove: string[]) => {
            const drop = new Set(remove);
            // Newest last, and capped, so tips that stopped firing long ago age out of the file.
            return [...new Set([...list.filter((v) => !drop.has(v) && !add.includes(v)), ...add])].slice(-500);
          };
          const tips = { hidden: apply(app.cfg.tips.hidden, ids("hide"), ids("unhide")), read: apply(app.cfg.tips.read, ids("read"), ids("unread")) };
          app.saveTipState(tips);
          return json(tips);
        }
        case "/api/pricing": {
          const rules = await jsonBody(req);
          if (!Array.isArray(rules)) return error("expected an array of price rules");
          const ins = app.db.prepare("INSERT OR REPLACE INTO pricing (pattern, input, output, cache_read, cache_write_5m, cache_write_1h) VALUES (?, ?, ?, ?, ?, ?)");
          app.db.transaction(() => {
            app.db.exec("DELETE FROM pricing");
            for (const r of rules as Record<string, unknown>[]) {
              const pattern = typeof r?.pattern === "string" ? r.pattern.trim().toLowerCase() : "";
              if (!pattern || pattern.length > 200 || !isPrice(r.input) || !isPrice(r.output)) continue;
              ins.run(pattern, r.input, r.output, optionalPrice(r.cacheRead), optionalPrice(r.cacheWrite5m), optionalPrice(r.cacheWrite1h));
            }
          })();
          app.reloadPrices();
          const updated = recomputeCosts(app.db, app.priceBook());
          return json({ updated });
        }
        case "/api/pick-folder": {
          // A native dialog on this desktop, which the request waits for. { start?, title? } -> { path } (null: cancelled).
          const body = ((await jsonBody(req)) ?? {}) as Record<string, unknown>;
          try {
            return json({ path: await picker.pick(body.start, body.title) });
          } catch (err) {
            if (err instanceof PickerBusy) return error("busy", 409);
            throw err;
          }
        }
        case "/api/db/compact":
          // VACUUM: rewrites the whole file, and no scan runs until it is done.
          return json(await app.compactDb());
        case "/api/digest": {
          // Write one now: the last 7 days by default, or last week's Monday to Sunday with ?week=last.
          const { digest, path } = app.writeDigest(pick(sp.get("week"), ["last", "this"] as const satisfies readonly DigestWeek[], "this"));
          return json({ path, ...digest });
        }
        case "/api/notify/test": {
          const lang = app.cfg.language;
          return json({ shown: await notify(message(lang, "title"), message(lang, "test")) });
        }
        case "/api/language": {
          // The UI's language, for the desktop alerts. Saved on its own: a settings change would restart the scanner.
          const lang = ((await jsonBody(req)) as { language?: unknown } | undefined)?.language;
          const parsed = parseSettings({ language: lang });
          if ("error" in parsed || !parsed.patch.language) return error("invalid value for language");
          if (parsed.patch.language !== app.cfg.language) app.saveLanguage(parsed.patch.language);
          return json({ language: app.cfg.language });
        }
        case "/api/shutdown":
          setTimeout(() => hooks.shutdown(), 100);
          return json({ ok: true });
        case "/api/update": {
          const result = await applyUpdate((m) => console.log(`[update] ${m}`));
          if (result.version !== VERSION) setTimeout(() => hooks.restart(), 300);
          return json({ ...result, restarting: result.version !== VERSION });
        }
      }
    }
    return error(`no route for ${method} ${url.pathname}`, 404);
  }

  /**
   * The live stream for a window without the sign-in cookie, e.g. one opened by 1.10 or older that just installed this
   * version and lost its server. A 401 would close its stream for good and leave it on "Restarting…" forever. A server
   * that says hello under another version is what such a window reloads on, into a page that says it isn't signed in.
   * Nothing else is sent, and the browser asks again only after an hour.
   */
  function signedOutEvents(): Response {
    return new Response(`retry: 3600000\ndata: ${JSON.stringify({ type: "hello", version: SIGNED_OUT })}\n\n`, {
      headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-store" },
    });
  }

  function events(req: Request): Response {
    let unsubscribe = () => {};
    let ping: ReturnType<typeof setInterval>;
    const stream = new ReadableStream({
      start(controller) {
        const enc = new TextEncoder();
        const send = (data: unknown) => controller.enqueue(enc.encode(`data: ${JSON.stringify(data)}\n\n`));
        send({ type: "hello", version: VERSION });
        unsubscribe = app.subscribe(send);
        ping = setInterval(() => controller.enqueue(enc.encode(": ping\n\n")), 20_000);
        req.signal.addEventListener("abort", () => {
          clearInterval(ping);
          unsubscribe();
          try {
            controller.close();
          } catch {
            /* already closed */
          }
        });
      },
      cancel() {
        clearInterval(ping);
        unsubscribe();
      },
    });
    return new Response(stream, { headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-store", Connection: "keep-alive" } });
  }
}
