import { existsSync } from "node:fs";
import { join, normalize } from "node:path";
import { importCursorCsv } from "../core/ingest/cursor.ts";
import { DbWriter, recomputeCosts } from "../core/ingest/writer.ts";
import { defaultDbPath } from "../core/paths.ts";
import type { Bucket, Dimension, Filters, Metric, SeriesGroup } from "../core/queries.ts";
import { SHARED_FOLDER, dbTarget, findSyncFolders } from "../core/syncFolders.ts";
import { generateTips } from "../core/tips.ts";
import { VERSION } from "../version.ts";
import type { App } from "./app.ts";
import { applyUpdate, checkForUpdate, isCompiledBinary } from "./update.ts";

const DIMENSIONS: Dimension[] = ["provider", "project", "user", "model", "skill", "agent", "session", "prompt", "host"];
const BUCKETS: Bucket[] = ["hour", "day", "week", "month"];
const GROUPS: SeriesGroup[] = ["none", "type", "provider", "project", "user", "model", "skill", "agent"];

export function parseFilters(sp: URLSearchParams): Filters {
  const n = (k: string) => {
    const v = sp.get(k);
    if (!v) return undefined;
    const x = Number(v);
    return Number.isFinite(x) ? x : undefined;
  };
  const s = (k: string) => sp.get(k) || undefined;
  return { from: n("from"), to: n("to"), provider: s("provider"), project: s("project"), user: s("user"), model: s("model"), skill: s("skill"), agent: s("agent") };
}

function pick<T extends string>(v: string | null, allowed: readonly T[], fallback: T): T {
  return v && (allowed as readonly string[]).includes(v) ? (v as T) : fallback;
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" },
  });
}

function error(message: string, status = 400): Response {
  return json({ error: message }, status);
}

export interface AssetSource {
  get(path: string): Promise<Response | null>;
}

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
  ".woff2": "font/woff2",
  ".webmanifest": "application/manifest+json",
};

export function mimeFor(path: string): string {
  const ext = path.slice(path.lastIndexOf("."));
  return MIME[ext] ?? "application/octet-stream";
}

/** Serves the built UI either from assets embedded in the binary or from web/dist on disk. */
export async function loadAssets(): Promise<AssetSource> {
  try {
    // Generated by scripts/build.ts right before `bun build --compile`; absent in dev checkouts.
    // @ts-ignore -- optional module
    const mod = (await import("./assets.generated.ts")) as { ASSETS: Record<string, string> };
    if (Object.keys(mod.ASSETS).length) {
      return {
        async get(path) {
          const file = mod.ASSETS[path];
          if (!file) return null;
          return new Response(Bun.file(file), { headers: { "Content-Type": mimeFor(path), "Cache-Control": path.startsWith("/assets/") ? "public, max-age=31536000, immutable" : "no-cache" } });
        },
      };
    }
  } catch {
    /* not generated: development checkout */
  }
  const dist = join(import.meta.dir, "..", "..", "web", "dist");
  return {
    async get(path) {
      const full = normalize(join(dist, path));
      if (!full.startsWith(dist) || !existsSync(full)) return null;
      return new Response(Bun.file(full), { headers: { "Content-Type": mimeFor(path), "Cache-Control": "no-cache" } });
    },
  };
}

export interface ServerHooks {
  /** Called after a self-update installed a new binary; should restart the process. */
  restart(): void;
  /** Stops the background server (the "Quit" button). */
  shutdown(): void;
}

/**
 * Guards against DNS-rebinding and cross-site requests: the Host header must be a loopback name,
 * and state-changing requests must carry a custom header (which forces a CORS preflight we never allow).
 */
function isAllowed(req: Request, url: URL): boolean {
  const host = (req.headers.get("host") ?? "").replace(/:\d+$/, "").replace(/^\[|\]$/g, "");
  if (!["localhost", "127.0.0.1", "::1"].includes(host)) return false;
  if (req.method !== "GET" && req.method !== "HEAD" && url.pathname.startsWith("/api/")) {
    return req.headers.get("x-harness-dashboard") === "1";
  }
  return true;
}

export function createHandler(app: App, assets: AssetSource, hooks: ServerHooks) {
  return async function handle(req: Request): Promise<Response> {
    const url = new URL(req.url);
    if (!isAllowed(req, url)) return error("forbidden", 403);
    const sp = url.searchParams;
    const path = url.pathname;

    try {
      if (path.startsWith("/api/")) return await api(req, url, path, sp);
      const res = (await assets.get(path === "/" ? "/index.html" : path)) ?? (await assets.get("/index.html"));
      return res ?? new Response("UI not built. Run `bun run build:web`.", { status: 404 });
    } catch (err) {
      console.error("[http]", err);
      return error((err as Error).message, 500);
    }
  };

  async function api(req: Request, url: URL, path: string, sp: URLSearchParams): Promise<Response> {
    const f = parseFilters(sp);
    const q = app.queries;
    const method = req.method;

    if (method === "GET") {
      switch (path) {
        case "/api/status":
          return json({
            version: VERSION,
            dbPath: app.dbPath,
            scanning: app.isScanning,
            lastScanAt: app.lastScanAt,
            lastScan: app.lastScan,
            identity: app.identity,
            compiled: isCompiledBinary(),
            platform: `${process.platform}-${process.arch}`,
          });
        case "/api/summary":
          return json(q.summary(f));
        case "/api/timeseries":
          return json(q.timeseries(f, pick(sp.get("bucket"), BUCKETS, "day"), pick(sp.get("group"), GROUPS, "type"), pick<Metric>(sp.get("metric"), ["tokens", "cost"], "tokens"), Number(sp.get("top") ?? 5)));
        case "/api/breakdown":
          return json(q.breakdown(f, pick(sp.get("dim"), DIMENSIONS, "project"), Math.min(500, Number(sp.get("limit") ?? 50)), pick(sp.get("sort"), ["tokens", "cost"] as const, "cost")));
        case "/api/billing":
          return json(q.billing(f));
        case "/api/heatmap":
          return json(q.heatmap(f, pick<Metric>(sp.get("metric"), ["tokens", "cost"], "tokens")));
        case "/api/calendar":
          return json(q.calendar(f));
        case "/api/sessions":
          return json(q.sessions(f, { sort: sp.get("sort") ?? undefined, limit: Math.min(200, Number(sp.get("limit") ?? 50)), offset: Number(sp.get("offset") ?? 0), q: sp.get("q") ?? undefined }));
        case "/api/session":
          return json(q.sessionDetail(sp.get("id") ?? ""));
        case "/api/prompts":
          return json(q.prompts(f, { sort: sp.get("sort") ?? undefined, limit: Math.min(200, Number(sp.get("limit") ?? 50)), offset: Number(sp.get("offset") ?? 0), q: sp.get("q") ?? undefined }));
        case "/api/prompts/costs":
          return json(q.promptCosts(f));
        case "/api/prompt":
          return json(q.promptDetail(sp.get("id") ?? ""));
        case "/api/tools":
          return json(q.tools(f));
        case "/api/files":
          return json(q.files(f));
        case "/api/files/hotspots":
          return json(q.hotspots(f));
        case "/api/files/list":
          return json(q.fileList(f, { sort: sp.get("sort") ?? undefined, limit: Math.min(200, Number(sp.get("limit") ?? 50)), offset: Number(sp.get("offset") ?? 0), q: sp.get("q") ?? undefined }));
        case "/api/cache":
          return json(q.cache(f, pick(sp.get("bucket"), BUCKETS, "day")));
        case "/api/tips":
          return json(generateTips(app.db, f, app.priceBook()));
        case "/api/filters":
          return json(q.filters(f));
        case "/api/settings":
          return json({ config: app.cfg, dbPath: app.dbPath, defaultDbPath: defaultDbPath(), syncFolders: findSyncFolders(), sharedFolder: SHARED_FOLDER });
        case "/api/settings/db-target":
          return json(dbTarget(sp.get("path") ?? "", app.dbPath, defaultDbPath()));
        case "/api/pricing":
          return json(app.priceBook().allRules());
        case "/api/update":
          return json(app.cfg.checkUpdates || sp.get("force") ? await checkForUpdate(sp.get("force") === "1") : { current: VERSION, available: false, disabled: true });
        case "/api/events":
          return events(req);
      }
    }

    if (method === "POST" || method === "PUT") {
      switch (path) {
        case "/api/scan": {
          const result = await app.scanNow(sp.get("full") === "1");
          return json(result);
        }
        case "/api/import/cursor": {
          const text = await req.text();
          const writer = new DbWriter(app.db, app.priceBook(), app.identity);
          let result;
          app.db.transaction(() => {
            result = importCursorCsv(text, writer);
          })();
          app.emit({ type: "scan", result: { filesSeen: 0, filesParsed: 1, usageRows: writer.stats.usage, prompts: 0, tools: 0, errors: [], durationMs: 0 } });
          return json(result);
        }
        case "/api/settings": {
          const body = (await req.json()) as Record<string, any>;
          const patch: Record<string, unknown> = {};
          for (const k of ["userName", "openMode", "scanIntervalSec", "promptTextLimit", "checkUpdates", "journalMode", "port"]) {
            if (k in body) patch[k] = body[k];
          }
          if (body.sources) patch.sources = body.sources;
          app.updateConfig(patch);
          if (typeof body.dbPath === "string") {
            const target = dbTarget(body.dbPath, app.dbPath, defaultDbPath());
            if (target.state === "missing" || target.state === "invalid") return error(`Can't use ${target.file}: ${target.state === "missing" ? "its folder doesn't exist" : "the path isn't absolute"}`);
            const file = target.state === "default" ? "" : target.file;
            if (target.state !== "current" && file !== app.cfg.dbPath) await app.switchDatabase(file, body.copyDb === true);
          }
          if (body.sources) app.scanNow().catch(() => {});
          return json({ config: app.cfg, dbPath: app.dbPath });
        }
        case "/api/pricing": {
          const rules = (await req.json()) as { pattern: string; input: number; output: number; cacheRead?: number | null; cacheWrite5m?: number | null; cacheWrite1h?: number | null }[];
          if (!Array.isArray(rules)) return error("expected an array of price rules");
          const ins = app.db.prepare("INSERT INTO pricing (pattern, input, output, cache_read, cache_write_5m, cache_write_1h) VALUES (?, ?, ?, ?, ?, ?)");
          app.db.transaction(() => {
            app.db.exec("DELETE FROM pricing");
            for (const r of rules) {
              if (!r.pattern || !Number.isFinite(r.input) || !Number.isFinite(r.output)) continue;
              ins.run(r.pattern.trim().toLowerCase(), r.input, r.output, r.cacheRead ?? null, r.cacheWrite5m ?? null, r.cacheWrite1h ?? null);
            }
          })();
          app.reloadPrices();
          const updated = recomputeCosts(app.db, app.priceBook());
          return json({ updated });
        }
        case "/api/shutdown":
          setTimeout(() => hooks.shutdown(), 100);
          return json({ ok: true });
        case "/api/update": {
          const result = await applyUpdate((m) => console.log(`[update] ${m}`));
          if (result.version !== VERSION) setTimeout(() => hooks.restart(), 300);
          return json({ ...result, restarting: result.version !== VERSION });
        }
      }
    }
    return error(`no route for ${method} ${url.pathname}`, 404);
  }

  function events(req: Request): Response {
    let unsubscribe = () => {};
    let ping: ReturnType<typeof setInterval>;
    const stream = new ReadableStream({
      start(controller) {
        const enc = new TextEncoder();
        const send = (data: unknown) => controller.enqueue(enc.encode(`data: ${JSON.stringify(data)}\n\n`));
        send({ type: "hello", version: VERSION });
        unsubscribe = app.subscribe(send);
        ping = setInterval(() => controller.enqueue(enc.encode(": ping\n\n")), 20_000);
        req.signal.addEventListener("abort", () => {
          clearInterval(ping);
          unsubscribe();
          try {
            controller.close();
          } catch {
            /* already closed */
          }
        });
      },
      cancel() {
        clearInterval(ping);
        unsubscribe();
      },
    });
    return new Response(stream, { headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-store", Connection: "keep-alive" } });
  }
}
