import type { AlertLang } from "./budgets.ts";

/**
 * The digest's wording in the UI languages, server side like the alerts of budgets.ts. {name} marks where a value goes.
 * No semicolons: the Markdown is meant to be read as it is.
 */
const MESSAGES: Record<AlertLang, Record<string, string>> = {
  en: {
    title: "Weekly digest",
    titleRolling: "Usage digest",
    period: "{from} to {to}",
    generated: "Harness Dashboard, written {when}",
    notifyTitle: "Your weekly digest is ready",
    notifyBody: "{cost} ({change}) and {tokens} tokens in {sessions} sessions. Open it in the dashboard under Settings.",
    colNow: "Last week",
    colPrev: "Week before",
    colNowRolling: "Last 7 days",
    colPrevRolling: "7 days before",
    colChange: "Change",
    cost: "Cost",
    tokens: "Tokens",
    sessions: "Sessions",
    prompts: "Prompts",
    lines: "Lines changed",
    per100: "Cost per 100 lines",
    projects: "Top projects",
    models: "Top models",
    providers: "Top providers",
    budgets: "Budgets",
    monthly: "Monthly budget",
    budgetLine: "{name}: {spent} of {cap} ({pct}) so far this month, on pace for {pace}",
    limits: "Plan limits",
    limitPeak: "{name}: peak {pct}",
    limitHits: "{name}: peak {pct}, used up in {n} cycles",
    limitsNone: "No limit readings in this period.",
    friction: "Failures",
    toolFailures: "Tool failures: {count} of {calls} calls ({rate})",
    topCauses: "Top causes: {list}",
    apiErrors: "API errors: {count}",
    noFailures: "No tool failures or API errors.",
    tips: "Tips",
    tipImpact: "about {cost} a month",
    noTips: "No tips right now.",
    noUsage: "No usage in this period.",
    none: "none",
  },
  de: {
    title: "Wochenrückblick",
    titleRolling: "Nutzungsrückblick",
    period: "{from} bis {to}",
    generated: "Harness Dashboard, erstellt {when}",
    notifyTitle: "Dein Wochenrückblick ist fertig",
    notifyBody: "{cost} ({change}) und {tokens} Tokens in {sessions} Sitzungen. Öffne ihn im Dashboard unter Einstellungen.",
    colNow: "Letzte Woche",
    colPrev: "Woche davor",
    colNowRolling: "Letzte 7 Tage",
    colPrevRolling: "7 Tage davor",
    colChange: "Änderung",
    cost: "Kosten",
    tokens: "Tokens",
    sessions: "Sitzungen",
    prompts: "Prompts",
    lines: "Geänderte Zeilen",
    per100: "Kosten pro 100 Zeilen",
    projects: "Top-Projekte",
    models: "Top-Modelle",
    providers: "Top-Anbieter",
    budgets: "Budgets",
    monthly: "Monatsbudget",
    budgetLine: "{name}: {spent} von {cap} ({pct}) bisher in diesem Monat, Prognose {pace}",
    limits: "Plan-Limits",
    limitPeak: "{name}: Spitze {pct}",
    limitHits: "{name}: Spitze {pct}, in {n} Zyklen aufgebraucht",
    limitsNone: "Keine Limit-Messwerte in diesem Zeitraum.",
    friction: "Fehler",
    toolFailures: "Tool-Fehler: {count} von {calls} Aufrufen ({rate})",
    topCauses: "Häufigste Ursachen: {list}",
    apiErrors: "API-Fehler: {count}",
    noFailures: "Keine Tool-Fehler und keine API-Fehler.",
    tips: "Tipps",
    tipImpact: "etwa {cost} im Monat",
    noTips: "Gerade keine Tipps.",
    noUsage: "Keine Nutzung in diesem Zeitraum.",
    none: "keine",
  },
  es: {
    title: "Resumen semanal",
    titleRolling: "Resumen de uso",
    period: "{from} a {to}",
    generated: "Harness Dashboard, creado {when}",
    notifyTitle: "Tu resumen semanal está listo",
    notifyBody: "{cost} ({change}) y {tokens} tokens en {sessions} sesiones. Ábrelo en el panel, en Ajustes.",
    colNow: "Semana pasada",
    colPrev: "Semana anterior",
    colNowRolling: "Últimos 7 días",
    colPrevRolling: "7 días anteriores",
    colChange: "Cambio",
    cost: "Coste",
    tokens: "Tokens",
    sessions: "Sesiones",
    prompts: "Prompts",
    lines: "Líneas cambiadas",
    per100: "Coste por 100 líneas",
    projects: "Proyectos principales",
    models: "Modelos principales",
    providers: "Proveedores principales",
    budgets: "Presupuestos",
    monthly: "Presupuesto mensual",
    budgetLine: "{name}: {spent} de {cap} ({pct}) en lo que va de mes, al ritmo de {pace}",
    limits: "Límites del plan",
    limitPeak: "{name}: máximo {pct}",
    limitHits: "{name}: máximo {pct}, agotado en {n} ciclos",
    limitsNone: "Sin lecturas de límites en este periodo.",
    friction: "Fallos",
    toolFailures: "Fallos de herramientas: {count} de {calls} llamadas ({rate})",
    topCauses: "Causas principales: {list}",
    apiErrors: "Errores de API: {count}",
    noFailures: "Sin fallos de herramientas ni errores de API.",
    tips: "Consejos",
    tipImpact: "unos {cost} al mes",
    noTips: "Ningún consejo por ahora.",
    noUsage: "Sin uso en este periodo.",
    none: "ninguno",
  },
  fr: {
    title: "Bilan de la semaine",
    titleRolling: "Bilan d'utilisation",
    period: "{from} au {to}",
    generated: "Harness Dashboard, créé {when}",
    notifyTitle: "Votre bilan de la semaine est prêt",
    notifyBody: "{cost} ({change}) et {tokens} tokens en {sessions} sessions. Ouvrez-le dans le tableau de bord, sous Réglages.",
    colNow: "Semaine dernière",
    colPrev: "Semaine précédente",
    colNowRolling: "7 derniers jours",
    colPrevRolling: "7 jours précédents",
    colChange: "Variation",
    cost: "Coût",
    tokens: "Tokens",
    sessions: "Sessions",
    prompts: "Prompts",
    lines: "Lignes modifiées",
    per100: "Coût pour 100 lignes",
    projects: "Principaux projets",
    models: "Principaux modèles",
    providers: "Principaux fournisseurs",
    budgets: "Budgets",
    monthly: "Budget mensuel",
    budgetLine: "{name} : {spent} sur {cap} ({pct}) depuis le début du mois, rythme de {pace}",
    limits: "Limites du forfait",
    limitPeak: "{name} : pic à {pct}",
    limitHits: "{name} : pic à {pct}, épuisée sur {n} cycles",
    limitsNone: "Aucune mesure de limite sur cette période.",
    friction: "Échecs",
    toolFailures: "Échecs d'outils : {count} sur {calls} appels ({rate})",
    topCauses: "Causes principales : {list}",
    apiErrors: "Erreurs d'API : {count}",
    noFailures: "Aucun échec d'outil ni erreur d'API.",
    tips: "Conseils",
    tipImpact: "environ {cost} par mois",
    noTips: "Aucun conseil pour le moment.",
    noUsage: "Aucune utilisation sur cette période.",
    none: "aucun",
  },
  pl: {
    title: "Podsumowanie tygodnia",
    titleRolling: "Podsumowanie użycia",
    period: "{from} do {to}",
    generated: "Harness Dashboard, utworzono {when}",
    notifyTitle: "Podsumowanie tygodnia jest gotowe",
    notifyBody: "{cost} ({change}) i {tokens} tokenów w {sessions} sesjach. Otwórz je w dashboardzie, w Ustawieniach.",
    colNow: "Zeszły tydzień",
    colPrev: "Tydzień wcześniej",
    colNowRolling: "Ostatnie 7 dni",
    colPrevRolling: "7 dni wcześniej",
    colChange: "Zmiana",
    cost: "Koszt",
    tokens: "Tokeny",
    sessions: "Sesje",
    prompts: "Prompty",
    lines: "Zmienione linie",
    per100: "Koszt na 100 linii",
    projects: "Najlepsze projekty",
    models: "Najlepsze modele",
    providers: "Najlepsi dostawcy",
    budgets: "Budżety",
    monthly: "Budżet miesięczny",
    budgetLine: "{name}: {spent} z {cap} ({pct}) w tym miesiącu, w tym tempie {pace}",
    limits: "Limity planu",
    limitPeak: "{name}: szczyt {pct}",
    limitHits: "{name}: szczyt {pct}, wyczerpany w {n} cyklach",
    limitsNone: "Brak odczytów limitów w tym okresie.",
    friction: "Błędy",
    toolFailures: "Błędy narzędzi: {count} z {calls} wywołań ({rate})",
    topCauses: "Główne przyczyny: {list}",
    apiErrors: "Błędy API: {count}",
    noFailures: "Brak błędów narzędzi i błędów API.",
    tips: "Wskazówki",
    tipImpact: "około {cost} miesięcznie",
    noTips: "Na razie brak wskazówek.",
    noUsage: "Brak użycia w tym okresie.",
    none: "brak",
  },
};

/** Tip titles and the reasons a tool call failed, as the UI words them (the titles of the Tips page, the friction view). */
const NAMES: Record<AlertLang, Record<string, string>> = {
  en: {
    "reason:timeout": "Timed out",
    "reason:edit_mismatch": "Edit didn't match the file",
    "reason:stale_read": "File not read or changed",
    "reason:not_found": "Not found",
    "reason:permission": "Permission denied",
    "reason:exit_code": "Command failed",
    "reason:bad_input": "Invalid input",
    "reason:other": "Other error",
    "reason:rejected": "Declined",
    "tip:low-cache-hit": "Low cache hit rate ({rate}%)",
    "tip:cache-write-heavy": "Cache writes are {share}% of spend",
    "tip:context-bloat": "Large context on every call (~{avg} tokens)",
    "tip:frequent-compactions": "Context was compacted {count} times",
    "tip:premium-small-prompts": "{count} small prompts on a premium model",
    "tip:project-concentration": "{project} uses {share}% of spend",
    "tip:subagent-share": "Subagents account for {share}% of cost",
    "tip:guardian-overhead": "Auto-review costs {share}% ({cost})",
    "tip:spike": "Spike on {day}: {ratio}× the usual",
    "tip:outlier-prompt": "One prompt cost {cost} ({ratio}× the median)",
    "tip:tool-loops": "{count} prompts with 150+ tool calls",
    "tip:repeated-reads": "{file} was read {count}× in one session",
    "tip:reasoning-heavy": "Reasoning is {share}% of output tokens",
    "tip:long-session": "Very long session: {messages} calls ({cost})",
    "tip:estimated-pricing": "{share}% of cost uses estimated prices",
    "tip:cache-expired": "The cache expired {count} times during a pause",
    "tip:model-switch": "Model switches rebuilt the cache {count} times",
    "tip:output-heavy": "Output is {share}% of spend",
    "tip:prompt-cost-rising": "A prompt now costs {ratio}× as much",
    "tip:repeated-prompt": "The same prompt was sent {count} times",
    "tip:edit-churn": "{file} was edited {count}× in one session",
    "tip:copilot-premium-pace": "On pace for {pace} Copilot premium requests a month",
  },
  de: {
    "reason:timeout": "Zeitüberschreitung",
    "reason:edit_mismatch": "Änderung passte nicht zur Datei",
    "reason:stale_read": "Datei nicht gelesen oder geändert",
    "reason:not_found": "Nicht gefunden",
    "reason:permission": "Keine Berechtigung",
    "reason:exit_code": "Befehl fehlgeschlagen",
    "reason:bad_input": "Ungültige Eingabe",
    "reason:other": "Anderer Fehler",
    "reason:rejected": "Abgelehnt",
    "tip:low-cache-hit": "Niedrige Cache-Trefferquote ({rate} %)",
    "tip:cache-write-heavy": "Cache-Schreiben macht {share} % der Kosten aus",
    "tip:context-bloat": "Großer Kontext bei jedem Aufruf (~{avg} Tokens)",
    "tip:frequent-compactions": "Kontext {count}-mal kompaktiert",
    "tip:premium-small-prompts": "{count} kleine Prompts auf einem Premium-Modell",
    "tip:project-concentration": "{project} verursacht {share} % der Kosten",
    "tip:subagent-share": "Subagents verursachen {share} % der Kosten",
    "tip:guardian-overhead": "Auto-Review kostet {share} % ({cost})",
    "tip:spike": "Spitze am {day}: {ratio}× so viel wie üblich",
    "tip:outlier-prompt": "Ein Prompt kostete {cost} ({ratio}× der Median)",
    "tip:tool-loops": "{count} Prompts mit über 150 Tool-Aufrufen",
    "tip:repeated-reads": "{file} wurde in einer Sitzung {count}× gelesen",
    "tip:reasoning-heavy": "Reasoning macht {share} % der Ausgabe-Tokens aus",
    "tip:long-session": "Sehr lange Sitzung: {messages} Aufrufe ({cost})",
    "tip:estimated-pricing": "{share} % der Kosten basieren auf geschätzten Preisen",
    "tip:cache-expired": "Der Cache ist {count}-mal in einer Pause abgelaufen",
    "tip:model-switch": "Modellwechsel haben den Cache {count}-mal neu aufgebaut",
    "tip:output-heavy": "Ausgabe macht {share} % der Kosten aus",
    "tip:prompt-cost-rising": "Ein Prompt kostet jetzt {ratio}× so viel",
    "tip:repeated-prompt": "Derselbe Prompt wurde {count}-mal gesendet",
    "tip:edit-churn": "{file} wurde in einer Sitzung {count}× bearbeitet",
    "tip:copilot-premium-pace": "Auf Kurs für {pace} Copilot-Premium-Anfragen im Monat",
  },
  es: {
    "reason:timeout": "Tiempo agotado",
    "reason:edit_mismatch": "La edición no coincidió con el archivo",
    "reason:stale_read": "Archivo sin leer o modificado",
    "reason:not_found": "No encontrado",
    "reason:permission": "Permiso denegado",
    "reason:exit_code": "El comando falló",
    "reason:bad_input": "Entrada no válida",
    "reason:other": "Otro error",
    "reason:rejected": "Rechazada",
    "tip:low-cache-hit": "Tasa de aciertos de caché baja ({rate} %)",
    "tip:cache-write-heavy": "Las escrituras en caché suponen el {share} % del gasto",
    "tip:context-bloat": "Contexto muy grande en cada llamada (~{avg} tokens)",
    "tip:frequent-compactions": "Contexto compactado {count} veces",
    "tip:premium-small-prompts": "{count} prompts pequeños en un modelo premium",
    "tip:project-concentration": "{project} supone el {share} % del gasto",
    "tip:subagent-share": "Los subagentes suponen el {share} % del coste",
    "tip:guardian-overhead": "La revisión automática cuesta el {share} % ({cost})",
    "tip:spike": "Pico el {day}: {ratio}× lo habitual",
    "tip:outlier-prompt": "Un prompt costó {cost} ({ratio}× la mediana)",
    "tip:tool-loops": "Prompts con más de 150 llamadas a herramientas: {count}",
    "tip:repeated-reads": "{file} se leyó {count}× en una sesión",
    "tip:reasoning-heavy": "El razonamiento supone el {share} % de los tokens de salida",
    "tip:long-session": "Sesión muy larga: {messages} llamadas ({cost})",
    "tip:estimated-pricing": "El {share} % del coste usa precios estimados",
    "tip:cache-expired": "La caché expiró {count} veces durante una pausa",
    "tip:model-switch": "Los cambios de modelo reconstruyeron la caché {count} veces",
    "tip:output-heavy": "La salida supone el {share} % del gasto",
    "tip:prompt-cost-rising": "Un prompt cuesta ahora {ratio}× lo de antes",
    "tip:repeated-prompt": "El mismo prompt se envió {count} veces",
    "tip:edit-churn": "{file} se editó {count}× en una sesión",
    "tip:copilot-premium-pace": "Al ritmo actual, {pace} solicitudes premium de Copilot al mes",
  },
  fr: {
    "reason:timeout": "Délai dépassé",
    "reason:edit_mismatch": "Modification non conforme au fichier",
    "reason:stale_read": "Fichier non lu ou modifié",
    "reason:not_found": "Introuvable",
    "reason:permission": "Permission refusée",
    "reason:exit_code": "Échec de la commande",
    "reason:bad_input": "Entrée non valide",
    "reason:other": "Autre erreur",
    "reason:rejected": "Refusé",
    "tip:low-cache-hit": "Taux de succès du cache faible ({rate} %)",
    "tip:cache-write-heavy": "Les écritures dans le cache représentent {share} % des dépenses",
    "tip:context-bloat": "Contexte volumineux à chaque appel (~{avg} tokens)",
    "tip:frequent-compactions": "Contexte compacté {count} fois",
    "tip:premium-small-prompts": "{count} petits prompts sur un modèle premium",
    "tip:project-concentration": "{project} représente {share} % des dépenses",
    "tip:subagent-share": "Les sous-agents représentent {share} % du coût",
    "tip:guardian-overhead": "La revue automatique coûte {share} % ({cost})",
    "tip:spike": "Pic le {day} : {ratio} fois la normale",
    "tip:outlier-prompt": "Un prompt a coûté {cost} ({ratio} fois la médiane)",
    "tip:tool-loops": "Prompts avec plus de 150 appels d'outils : {count}",
    "tip:repeated-reads": "{file} lu {count} fois dans une même session",
    "tip:reasoning-heavy": "Le raisonnement représente {share} % des tokens de sortie",
    "tip:long-session": "Session très longue : {messages} appels ({cost})",
    "tip:estimated-pricing": "{share} % du coût repose sur des prix estimés",
    "tip:cache-expired": "Le cache a expiré {count} fois pendant une pause",
    "tip:model-switch": "Les changements de modèle ont reconstruit le cache {count} fois",
    "tip:output-heavy": "La sortie représente {share} % des dépenses",
    "tip:prompt-cost-rising": "Un prompt coûte désormais {ratio} fois plus cher",
    "tip:repeated-prompt": "Le même prompt a été envoyé {count} fois",
    "tip:edit-churn": "{file} modifié {count} fois dans une même session",
    "tip:copilot-premium-pace": "Au rythme actuel, {pace} requêtes premium Copilot par mois",
  },
  pl: {
    "reason:timeout": "Przekroczony czas",
    "reason:edit_mismatch": "Edycja nie pasowała do pliku",
    "reason:stale_read": "Plik nieprzeczytany lub zmieniony",
    "reason:not_found": "Nie znaleziono",
    "reason:permission": "Brak uprawnień",
    "reason:exit_code": "Polecenie nie powiodło się",
    "reason:bad_input": "Nieprawidłowe dane wejściowe",
    "reason:other": "Inny błąd",
    "reason:rejected": "Odrzucone",
    "tip:low-cache-hit": "Niski współczynnik trafień w cache ({rate}%)",
    "tip:cache-write-heavy": "Zapisy do cache to {share}% wydatków",
    "tip:context-bloat": "Duży kontekst w każdym wywołaniu (~{avg} tokenów)",
    "tip:frequent-compactions": "Liczba kompaktowań kontekstu: {count}",
    "tip:premium-small-prompts": "Małe prompty na modelu premium: {count}",
    "tip:project-concentration": "{project} odpowiada za {share}% wydatków",
    "tip:subagent-share": "Subagenci odpowiadają za {share}% kosztu",
    "tip:guardian-overhead": "Automatyczne przeglądy kosztują {share}% ({cost})",
    "tip:spike": "Skok w dniu {day}: {ratio}× więcej niż zwykle",
    "tip:outlier-prompt": "Jeden prompt kosztował {cost} ({ratio}× mediany)",
    "tip:tool-loops": "Prompty z ponad 150 wywołaniami narzędzi: {count}",
    "tip:repeated-reads": "Plik {file} odczytano {count}× w jednej sesji",
    "tip:reasoning-heavy": "Rozumowanie to {share}% tokenów wyjściowych",
    "tip:long-session": "Bardzo długa sesja ({cost}), liczba wywołań: {messages}",
    "tip:estimated-pricing": "{share}% kosztu opiera się na szacowanych cenach",
    "tip:cache-expired": "Cache wygasał podczas przerw {count} razy",
    "tip:model-switch": "Zmiany modelu odbudowały cache {count} razy",
    "tip:output-heavy": "Wyjście to {share}% wydatków",
    "tip:prompt-cost-rising": "Prompt kosztuje teraz {ratio}× tyle co wcześniej",
    "tip:repeated-prompt": "Ten sam prompt wysłano {count} razy",
    "tip:edit-churn": "Plik {file} edytowano {count}× w jednej sesji",
    "tip:copilot-premium-pace": "Prognoza zapytań premium Copilot: {pace} miesięcznie",
  },
};

/** A message in `lang`, English when it has none. */
export function digestText(lang: AlertLang, key: string, params: Record<string, string | number> = {}): string {
  const text = MESSAGES[lang]?.[key] ?? MESSAGES.en[key] ?? key;
  return text.replace(/\{(\w+)\}/g, (_, k: string) => String(params[k] ?? ""));
}

/** The title of a tip (`tip:<id>`) or the name of a failure reason (`reason:<id>`), or null when unknown. */
export function digestName(lang: AlertLang, key: string): string | null {
  return NAMES[lang]?.[key] ?? NAMES.en[key] ?? null;
}
