#!/usr/bin/env bun
/**
 * Builds the UI, embeds it into the server and compiles standalone executables.
 *
 *   bun run build          → binary for the current platform in dist/
 *   bun run build --all    → binaries for every supported platform + checksums.txt
 *   bun run build --target bun-linux-arm64
 */
import { $ } from "bun";
import { existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { BIN_NAME, VERSION } from "../src/version.ts";

const ROOT = join(import.meta.dir, "..");
const DIST_WEB = join(ROOT, "web", "dist");
const OUT = join(ROOT, "dist");
const GENERATED = join(ROOT, "src", "server", "assets.generated.ts");

const TARGETS = ["bun-linux-x64", "bun-linux-arm64", "bun-darwin-x64", "bun-darwin-arm64", "bun-windows-x64"] as const;

function hostTarget(): string {
  const os = process.platform === "win32" ? "windows" : process.platform;
  return `bun-${os}-${process.arch === "arm64" ? "arm64" : "x64"}`;
}

function outName(target: string): string {
  const [, os, arch] = target.split("-");
  return `${BIN_NAME}-${os}-${arch}${os === "windows" ? ".exe" : ""}`;
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

function generateAssetsModule(): void {
  const files = walk(DIST_WEB).sort();
  const imports: string[] = [];
  const entries: string[] = [];
  files.forEach((file, i) => {
    const rel = relative(join(ROOT, "src", "server"), file).split("\\").join("/");
    const url = "/" + relative(DIST_WEB, file).split("\\").join("/");
    imports.push(`import a${i} from ${JSON.stringify(rel)} with { type: "file" };`);
    entries.push(`  ${JSON.stringify(url)}: a${i},`);
  });
  writeFileSync(
    GENERATED,
    `// AUTO-GENERATED by scripts/build.ts — do not edit or commit.\n${imports.join("\n")}\n\nexport const ASSETS: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
  );
  console.log(`  embedded ${files.length} UI files`);
}

async function sha256(path: string): Promise<string> {
  return new Bun.CryptoHasher("sha256").update(await Bun.file(path).arrayBuffer()).digest("hex");
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const targetIdx = args.indexOf("--target");
  const targets: string[] = args.includes("--all") ? [...TARGETS] : targetIdx >= 0 ? [args[targetIdx + 1]!] : [hostTarget()];

  console.log(`Building ${BIN_NAME} ${VERSION}`);
  console.log("→ UI");
  await $`bunx vite build --config web/vite.config.ts --logLevel warn`.cwd(ROOT);
  if (!existsSync(join(DIST_WEB, "index.html"))) throw new Error("UI build produced no index.html");

  generateAssetsModule();
  mkdirSync(OUT, { recursive: true });
  try {
    for (const target of targets) {
      const out = join(OUT, outName(target));
      console.log(`→ ${target}`);
      await $`bun build src/cli.ts --compile --minify --sourcemap=none --target=${target} --outfile ${out}`.cwd(ROOT).quiet();
      if (target.includes("darwin") && process.platform === "darwin") {
        // Ad-hoc sign before checksumming: Apple Silicon refuses unsigned executables.
        await $`codesign --force --sign - ${out}`.quiet();
      }
      console.log(`  ${relative(ROOT, out)} (${(statSync(out).size / 1e6).toFixed(1)} MB)`);
    }
  } finally {
    rmSync(GENERATED, { force: true });
  }

  if (targets.length > 1) {
    const lines: string[] = [];
    for (const target of targets) {
      const name = outName(target);
      lines.push(`${await sha256(join(OUT, name))}  ${name}`);
    }
    writeFileSync(join(OUT, "checksums.txt"), lines.join("\n") + "\n");
    console.log("  dist/checksums.txt");
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
